// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './ColorWheel.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, ColorWheelSpec, ColorWheelKernel, AppCore };
`);

const { _dafny, ColorWheelSpec, ColorWheelKernel, AppCore } = initDafny(require);


// ============================================================================
// Helpers
// ============================================================================

// Convert Dafny seq to JS array
const seqToArray = (seq) => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// Convert BigNumber to JS number
const toNumber = (bn) => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};

// Convert Dafny string to JS string
const dafnyStringToJs = (seq) => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};

// ============================================================================
// Datatype Conversions
// ============================================================================

const colorFromJson = (json) => {
  return ColorWheelSpec.Color.create_Color(
    new BigNumber(json.h),
    new BigNumber(json.s),
    new BigNumber(json.l)
  );
};

const colorToJson = (value) => {
  return {
    h: toNumber(value.dtor_h),
    s: toNumber(value.dtor_s),
    l: toNumber(value.dtor_l)
  };
};

const moodFromJson = (json) => {
  switch (json) {
    case 'Vibrant':
      return ColorWheelSpec.Mood.create_Vibrant();
    case 'SoftMuted':
      return ColorWheelSpec.Mood.create_SoftMuted();
    case 'Pastel':
      return ColorWheelSpec.Mood.create_Pastel();
    case 'DeepJewel':
      return ColorWheelSpec.Mood.create_DeepJewel();
    case 'Earth':
      return ColorWheelSpec.Mood.create_Earth();
    case 'Neon':
      return ColorWheelSpec.Mood.create_Neon();
    case 'Custom':
      return ColorWheelSpec.Mood.create_Custom();
    default:
      throw new Error(`Unknown Mood: ${json}`);
  }
};

const moodToJson = (value) => {
  if (value.is_Vibrant) {
    return 'Vibrant';
  } else if (value.is_SoftMuted) {
    return 'SoftMuted';
  } else if (value.is_Pastel) {
    return 'Pastel';
  } else if (value.is_DeepJewel) {
    return 'DeepJewel';
  } else if (value.is_Earth) {
    return 'Earth';
  } else if (value.is_Neon) {
    return 'Neon';
  } else if (value.is_Custom) {
    return 'Custom';
  }
  return 'Unknown';
};

const harmonyFromJson = (json) => {
  switch (json) {
    case 'Complementary':
      return ColorWheelSpec.Harmony.create_Complementary();
    case 'Triadic':
      return ColorWheelSpec.Harmony.create_Triadic();
    case 'Analogous':
      return ColorWheelSpec.Harmony.create_Analogous();
    case 'SplitComplement':
      return ColorWheelSpec.Harmony.create_SplitComplement();
    case 'Square':
      return ColorWheelSpec.Harmony.create_Square();
    case 'Custom':
      return ColorWheelSpec.Harmony.create_Custom();
    default:
      throw new Error(`Unknown Harmony: ${json}`);
  }
};

const harmonyToJson = (value) => {
  if (value.is_Complementary) {
    return 'Complementary';
  } else if (value.is_Triadic) {
    return 'Triadic';
  } else if (value.is_Analogous) {
    return 'Analogous';
  } else if (value.is_SplitComplement) {
    return 'SplitComplement';
  } else if (value.is_Square) {
    return 'Square';
  } else if (value.is_Custom) {
    return 'Custom';
  }
  return 'Unknown';
};

const modelFromJson = (json) => {
  return ColorWheelSpec.Model.create_Model(
    new BigNumber(json.baseHue),
    moodFromJson(json.mood),
    harmonyFromJson(json.harmony),
    _dafny.Seq.of(...(json.colors || []).map(x => colorFromJson(x))),
    _dafny.Tuple.create_2(new BigNumber(json.contrastPair[0]), new BigNumber(json.contrastPair[1])),
    new BigNumber(json.adjustmentH),
    new BigNumber(json.adjustmentS),
    new BigNumber(json.adjustmentL)
  );
};

const modelToJson = (value) => {
  return {
    baseHue: toNumber(value.dtor_baseHue),
    mood: moodToJson(value.dtor_mood),
    harmony: harmonyToJson(value.dtor_harmony),
    colors: seqToArray(value.dtor_colors).map(x => colorToJson(x)),
    contrastPair: [toNumber(value.dtor_contrastPair[0]), toNumber(value.dtor_contrastPair[1])],
    adjustmentH: toNumber(value.dtor_adjustmentH),
    adjustmentS: toNumber(value.dtor_adjustmentS),
    adjustmentL: toNumber(value.dtor_adjustmentL)
  };
};

const actionFromJson = (json) => {
  switch (json.type) {
    case 'GeneratePalette':
      return ColorWheelSpec.Action.create_GeneratePalette(
        new BigNumber(json.baseHue),
        moodFromJson(json.mood),
        harmonyFromJson(json.harmony),
        _dafny.Seq.of(...(json.randomSeeds || []).map(x => new BigNumber(x)))
      );
    case 'AdjustColor':
      return ColorWheelSpec.Action.create_AdjustColor(
        new BigNumber(json.index),
        new BigNumber(json.deltaH),
        new BigNumber(json.deltaS),
        new BigNumber(json.deltaL)
      );
    case 'AdjustPalette':
      return ColorWheelSpec.Action.create_AdjustPalette(
        new BigNumber(json.deltaH),
        new BigNumber(json.deltaS),
        new BigNumber(json.deltaL)
      );
    case 'SelectContrastPair':
      return ColorWheelSpec.Action.create_SelectContrastPair(
        new BigNumber(json.fg),
        new BigNumber(json.bg)
      );
    case 'SetColorDirect':
      return ColorWheelSpec.Action.create_SetColorDirect(
        new BigNumber(json.index),
        colorFromJson(json.color)
      );
    case 'RegenerateMood':
      return ColorWheelSpec.Action.create_RegenerateMood(
        moodFromJson(json.mood),
        _dafny.Seq.of(...(json.randomSeeds || []).map(x => new BigNumber(x)))
      );
    case 'RegenerateHarmony':
      return ColorWheelSpec.Action.create_RegenerateHarmony(
        harmonyFromJson(json.harmony),
        _dafny.Seq.of(...(json.randomSeeds || []).map(x => new BigNumber(x)))
      );
    case 'RandomizeBaseHue':
      return ColorWheelSpec.Action.create_RandomizeBaseHue(
        new BigNumber(json.newBaseHue),
        _dafny.Seq.of(...(json.randomSeeds || []).map(x => new BigNumber(x)))
      );
    default:
      throw new Error(`Unknown Action type: ${json.type}`);
  }
};

const actionToJson = (value) => {
  if (value.is_GeneratePalette) {
    return {
      type: 'GeneratePalette',
      baseHue: toNumber(value.dtor_baseHue),
      mood: moodToJson(value.dtor_mood),
      harmony: harmonyToJson(value.dtor_harmony),
      randomSeeds: seqToArray(value.dtor_randomSeeds).map(x => toNumber(x))
    };
  } else if (value.is_AdjustColor) {
    return {
      type: 'AdjustColor',
      index: toNumber(value.dtor_index),
      deltaH: toNumber(value.dtor_deltaH),
      deltaS: toNumber(value.dtor_deltaS),
      deltaL: toNumber(value.dtor_deltaL)
    };
  } else if (value.is_AdjustPalette) {
    return {
      type: 'AdjustPalette',
      deltaH: toNumber(value.dtor_deltaH),
      deltaS: toNumber(value.dtor_deltaS),
      deltaL: toNumber(value.dtor_deltaL)
    };
  } else if (value.is_SelectContrastPair) {
    return {
      type: 'SelectContrastPair',
      fg: toNumber(value.dtor_fg),
      bg: toNumber(value.dtor_bg)
    };
  } else if (value.is_SetColorDirect) {
    return {
      type: 'SetColorDirect',
      index: toNumber(value.dtor_index),
      color: colorToJson(value.dtor_color)
    };
  } else if (value.is_RegenerateMood) {
    return {
      type: 'RegenerateMood',
      mood: moodToJson(value.dtor_mood),
      randomSeeds: seqToArray(value.dtor_randomSeeds).map(x => toNumber(x))
    };
  } else if (value.is_RegenerateHarmony) {
    return {
      type: 'RegenerateHarmony',
      harmony: harmonyToJson(value.dtor_harmony),
      randomSeeds: seqToArray(value.dtor_randomSeeds).map(x => toNumber(x))
    };
  } else if (value.is_RandomizeBaseHue) {
    return {
      type: 'RandomizeBaseHue',
      newBaseHue: toNumber(value.dtor_newBaseHue),
      randomSeeds: seqToArray(value.dtor_randomSeeds).map(x => toNumber(x))
    };
  }
  return { type: 'Unknown' };
};

const historyFromJson = (json) => {
  return ColorWheelKernel.History.create_History(
    _dafny.Seq.of(...(json.past || []).map(x => modelFromJson(x))),
    modelFromJson(json.present),
    _dafny.Seq.of(...(json.future || []).map(x => modelFromJson(x)))
  );
};

const historyToJson = (value) => {
  return {
    past: seqToArray(value.dtor_past).map(x => modelToJson(x)),
    present: modelToJson(value.dtor_present),
    future: seqToArray(value.dtor_future).map(x => modelToJson(x))
  };
};

// ============================================================================
// API Wrapper
// ============================================================================

const App = {
  // Color constructors
  Color: (h, s, l) => ColorWheelSpec.Color.create_Color(new BigNumber(h), new BigNumber(s), new BigNumber(l)),

  // Mood constructors
  Vibrant: () => ColorWheelSpec.Mood.create_Vibrant(),
  SoftMuted: () => ColorWheelSpec.Mood.create_SoftMuted(),
  Pastel: () => ColorWheelSpec.Mood.create_Pastel(),
  DeepJewel: () => ColorWheelSpec.Mood.create_DeepJewel(),
  Earth: () => ColorWheelSpec.Mood.create_Earth(),
  Neon: () => ColorWheelSpec.Mood.create_Neon(),
  Custom: () => ColorWheelSpec.Mood.create_Custom(),

  // Harmony constructors
  Complementary: () => ColorWheelSpec.Harmony.create_Complementary(),
  Triadic: () => ColorWheelSpec.Harmony.create_Triadic(),
  Analogous: () => ColorWheelSpec.Harmony.create_Analogous(),
  SplitComplement: () => ColorWheelSpec.Harmony.create_SplitComplement(),
  Square: () => ColorWheelSpec.Harmony.create_Square(),
  Custom: () => ColorWheelSpec.Harmony.create_Custom(),

  // Action constructors
  GeneratePalette: (baseHue, mood, harmony, randomSeeds) => ColorWheelSpec.Action.create_GeneratePalette(new BigNumber(baseHue), mood, harmony, _dafny.Seq.of(...(randomSeeds || []).map(x => new BigNumber(x)))),
  AdjustColor: (index, deltaH, deltaS, deltaL) => ColorWheelSpec.Action.create_AdjustColor(new BigNumber(index), new BigNumber(deltaH), new BigNumber(deltaS), new BigNumber(deltaL)),
  AdjustPalette: (deltaH, deltaS, deltaL) => ColorWheelSpec.Action.create_AdjustPalette(new BigNumber(deltaH), new BigNumber(deltaS), new BigNumber(deltaL)),
  SelectContrastPair: (fg, bg) => ColorWheelSpec.Action.create_SelectContrastPair(new BigNumber(fg), new BigNumber(bg)),
  SetColorDirect: (index, color) => ColorWheelSpec.Action.create_SetColorDirect(new BigNumber(index), color),
  RegenerateMood: (mood, randomSeeds) => ColorWheelSpec.Action.create_RegenerateMood(mood, _dafny.Seq.of(...(randomSeeds || []).map(x => new BigNumber(x)))),
  RegenerateHarmony: (harmony, randomSeeds) => ColorWheelSpec.Action.create_RegenerateHarmony(harmony, _dafny.Seq.of(...(randomSeeds || []).map(x => new BigNumber(x)))),
  RandomizeBaseHue: (newBaseHue, randomSeeds) => ColorWheelSpec.Action.create_RandomizeBaseHue(new BigNumber(newBaseHue), _dafny.Seq.of(...(randomSeeds || []).map(x => new BigNumber(x)))),

  // Model accessors
  GetBaseHue: (m) => toNumber(m.dtor_baseHue),
  GetMood: (m) => moodToJson(m.dtor_mood),
  GetHarmony: (m) => harmonyToJson(m.dtor_harmony),
  GetColors: (m) => seqToArray(m.dtor_colors).map(x => colorToJson(x)),
  GetContrastPair: (m) => [toNumber(m.dtor_contrastPair[0]), toNumber(m.dtor_contrastPair[1])],
  GetAdjustmentH: (m) => toNumber(m.dtor_adjustmentH),
  GetAdjustmentS: (m) => toNumber(m.dtor_adjustmentS),
  GetAdjustmentL: (m) => toNumber(m.dtor_adjustmentL),

  // AppCore functions
  Init: () => AppCore.__default.Init(),
  Dispatch: (h, a) => AppCore.__default.Dispatch(h, a),
  Preview: (h, a) => AppCore.__default.Preview(h, a),
  CommitFrom: (h, baseline) => AppCore.__default.CommitFrom(h, baseline),
  Undo: (h) => AppCore.__default.Undo(h),
  Redo: (h) => AppCore.__default.Redo(h),
  Present: (h) => AppCore.__default.Present(h),
  CanUndo: (h) => AppCore.__default.CanUndo(h),
  CanRedo: (h) => AppCore.__default.CanRedo(h),

  // Conversion functions
  colorToJson: colorToJson,
  colorFromJson: colorFromJson,
  moodToJson: moodToJson,
  moodFromJson: moodFromJson,
  harmonyToJson: harmonyToJson,
  harmonyFromJson: harmonyFromJson,
  modelToJson: modelToJson,
  modelFromJson: modelFromJson,
  actionToJson: actionToJson,
  actionFromJson: actionFromJson,
  historyToJson: historyToJson,
  historyFromJson: historyFromJson,
};

// Export internals for custom extensions
App._internal = { _dafny, ColorWheelSpec, ColorWheelKernel, AppCore };

export default App;
