// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './Counter.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, CounterDomain, CounterKernel, AppCore };
`);

const { _dafny, CounterDomain, CounterKernel, AppCore } = initDafny(require);


// ============================================================================
// Helpers
// ============================================================================

// Convert Dafny seq to JS array
const seqToArray = (seq) => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// Convert BigNumber to JS number
const toNumber = (bn) => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};

// Convert Dafny string to JS string
const dafnyStringToJs = (seq) => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};

// ============================================================================
// Datatype Conversions
// ============================================================================

const actionFromJson = (json) => {
  switch (json) {
    case 'Inc':
      return CounterDomain.Action.create_Inc();
    case 'Dec':
      return CounterDomain.Action.create_Dec();
    default:
      throw new Error(`Unknown Action: ${json}`);
  }
};

const actionToJson = (value) => {
  if (value.is_Inc) {
    return 'Inc';
  } else if (value.is_Dec) {
    return 'Dec';
  }
  return 'Unknown';
};

const historyFromJson = (json) => {
  return CounterKernel.History.create_History(
    _dafny.Seq.of(...(json.past || []).map(x => new BigNumber(x))),
    new BigNumber(json.present),
    _dafny.Seq.of(...(json.future || []).map(x => new BigNumber(x)))
  );
};

const historyToJson = (value) => {
  return {
    past: seqToArray(value.dtor_past).map(x => toNumber(x)),
    present: toNumber(value.dtor_present),
    future: seqToArray(value.dtor_future).map(x => toNumber(x))
  };
};

// ============================================================================
// API Wrapper
// ============================================================================

const App = {
  // Action constructors
  Inc: () => CounterDomain.Action.create_Inc(),
  Dec: () => CounterDomain.Action.create_Dec(),

  // AppCore functions
  Init: () => AppCore.__default.Init(),
  Dispatch: (h, a) => AppCore.__default.Dispatch(h, a),
  Undo: (h) => AppCore.__default.Undo(h),
  Redo: (h) => AppCore.__default.Redo(h),
  Present: (h) => toNumber(AppCore.__default.Present(h)),
  CanUndo: (h) => AppCore.__default.CanUndo(h),
  CanRedo: (h) => AppCore.__default.CanRedo(h),

  // Conversion functions
  actionToJson: actionToJson,
  actionFromJson: actionFromJson,
  historyToJson: historyToJson,
  historyFromJson: historyFromJson,
};

// Export internals for custom extensions
App._internal = { _dafny, CounterDomain, CounterKernel, AppCore };

export default App;
