// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './Counter.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod: string) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, CounterDomain, CounterKernel, AppCore };
`);

const { _dafny, CounterDomain, CounterKernel, AppCore } = initDafny(require);

// ============================================================================
// Helpers
// ============================================================================

// deno-lint-ignore no-explicit-any
const seqToArray = (seq: any): any[] => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// deno-lint-ignore no-explicit-any
const toNumber = (bn: any): number => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};


// ============================================================================
// TypeScript Type Definitions (JSON representation)
// ============================================================================

export type Action = 'Inc' | 'Dec';

export interface History {
  past: number[];
  present: number;
  future: number[];
}

// ============================================================================
// Dafny Runtime Types (actual Dafny runtime object shapes)
// ============================================================================

// Base Dafny runtime types
type DafnyInt = InstanceType<typeof BigNumber>;
interface DafnySeq<T = unknown> {
  readonly length: number;
  readonly [index: number]: T;
  toVerbatimString?(asLiteral: boolean): string;
  map<U>(fn: (x: T) => U): U[];
}

type DafnyAction = { readonly is_Inc: true; readonly is_Dec: false } | { readonly is_Inc: false; readonly is_Dec: true };

interface DafnyHistory {
  readonly is_History: true;
  readonly dtor_past: DafnySeq<DafnyInt>;
  readonly dtor_present: DafnyInt;
  readonly dtor_future: DafnySeq<DafnyInt>;
}

// ============================================================================
// Datatype Conversions
// ============================================================================

// deno-lint-ignore no-explicit-any
const actionFromJson = (json: any): DafnyAction => {
  switch (json) {
    case 'Inc':
      return CounterDomain.Action.create_Inc();
    case 'Dec':
      return CounterDomain.Action.create_Dec();
    default:
      throw new Error(`Unknown Action: ${json}`);
  }
};

// deno-lint-ignore no-explicit-any
const actionToJson = (value: any): Action => {
  if (value.is_Inc) {
    return 'Inc';
  } else if (value.is_Dec) {
    return 'Dec';
  }
  throw new Error('Unknown Action variant');
};

// deno-lint-ignore no-explicit-any
const historyFromJson = (json: any): DafnyHistory => {
  return CounterKernel.History.create_History(
    _dafny.Seq.of(...(json.past || []).map((x: any) => new BigNumber(x))),
    new BigNumber(json.present),
    _dafny.Seq.of(...(json.future || []).map((x: any) => new BigNumber(x)))
  );
};

// deno-lint-ignore no-explicit-any
const historyToJson = (value: any): History => {
  return {
    past: seqToArray(value.dtor_past).map((x: any) => toNumber(x)),
    present: toNumber(value.dtor_present),
    future: seqToArray(value.dtor_future).map((x: any) => toNumber(x))
  };
};

// ============================================================================
// API Wrapper
// ============================================================================

interface AppInternal { _dafny: unknown; CounterDomain: unknown; CounterKernel: unknown; AppCore: unknown; }

const App = {
  // Action constructors
  Inc: () => CounterDomain.Action.create_Inc(),
  Dec: () => CounterDomain.Action.create_Dec(),

  // AppCore functions
  Init: (): DafnyHistory => AppCore.__default.Init(),
  Dispatch: (h: DafnyHistory, a: DafnyAction): DafnyHistory => AppCore.__default.Dispatch(h, a),
  Undo: (h: DafnyHistory): DafnyHistory => AppCore.__default.Undo(h),
  Redo: (h: DafnyHistory): DafnyHistory => AppCore.__default.Redo(h),
  Present: (h: DafnyHistory): number => toNumber(AppCore.__default.Present(h)),
  CanUndo: (h: DafnyHistory): boolean => AppCore.__default.CanUndo(h),
  CanRedo: (h: DafnyHistory): boolean => AppCore.__default.CanRedo(h),

  // Conversion functions
  actionToJson,
  actionFromJson,
  historyToJson,
  historyFromJson,

  // Internal modules for custom extensions
  _internal: { _dafny, CounterDomain, CounterKernel, AppCore } as AppInternal,
};

export default App;
