// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './DelegationAuth.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, DelegationAuthDomain, DelegationAuthKernel, DelegationAuthAppCore };
`);

const { _dafny, DelegationAuthDomain, DelegationAuthKernel, DelegationAuthAppCore } = initDafny(require);

// ============================================================================
// Helpers
// ============================================================================

const seqToArray = (seq) => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

const toNumber = (bn) => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};

const dafnyStringToJs = (seq) => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};


// ============================================================================
// Datatype Conversions
// ============================================================================

const delegFromJson = (json) => {
  return DelegationAuthDomain.Deleg.create_Deleg(
    _dafny.Seq.UnicodeFromString(json.from),
    _dafny.Seq.UnicodeFromString(json.to),
    _dafny.Seq.UnicodeFromString(json.cap)
  );
};

const delegToJson = (value) => {
  return {
    from: dafnyStringToJs(value.dtor_from),
    to: dafnyStringToJs(value.dtor_to),
    cap: dafnyStringToJs(value.dtor_cap)
  };
};

const modelFromJson = (json) => {
  let __delegations = _dafny.Map.Empty;
  for (const [k, v] of Object.entries(json.delegations || {})) {
    const key = new BigNumber(k);
    const val = delegFromJson(v);
    __delegations = __delegations.update(key, val);
  }
  return DelegationAuthDomain.Model.create_Model(
    _dafny.Set.fromElements(...(json.subjects || []).map(x => _dafny.Seq.UnicodeFromString(x))),
    _dafny.Set.fromElements(...(json.grants || []).map(x => _dafny.Tuple.create_2(_dafny.Seq.UnicodeFromString(x[0]), _dafny.Seq.UnicodeFromString(x[1])))),
    __delegations,
    new BigNumber(json.nextEdge)
  );
};

const modelToJson = (value) => {
  const __delegationsJson = {};
  if (value.dtor_delegations && value.dtor_delegations.Keys) {
    for (const k of value.dtor_delegations.Keys.Elements) {
      const v = value.dtor_delegations.get(k);
      __delegationsJson[toNumber(k)] = delegToJson(v);
    }
  }
  return {
    subjects: Array.from(value.dtor_subjects.Elements).map(x => dafnyStringToJs(x)),
    grants: Array.from(value.dtor_grants.Elements).map(x => [dafnyStringToJs(x[0]), dafnyStringToJs(x[1])]),
    delegations: __delegationsJson,
    nextEdge: toNumber(value.dtor_nextEdge)
  };
};

const actionFromJson = (json) => {
  switch (json.type) {
    case 'AddSubject': {
      return DelegationAuthDomain.Action.create_AddSubject(
        _dafny.Seq.UnicodeFromString(json.s)
      );
    }
    case 'Grant': {
      return DelegationAuthDomain.Action.create_Grant(
        _dafny.Seq.UnicodeFromString(json.s),
        _dafny.Seq.UnicodeFromString(json.cap)
      );
    }
    case 'Delegate': {
      return DelegationAuthDomain.Action.create_Delegate(
        _dafny.Seq.UnicodeFromString(json.from),
        _dafny.Seq.UnicodeFromString(json.to),
        _dafny.Seq.UnicodeFromString(json.cap)
      );
    }
    case 'Revoke': {
      return DelegationAuthDomain.Action.create_Revoke(
        new BigNumber(json.eid)
      );
    }
    default:
      throw new Error(`Unknown Action type: ${json.type}`);
  }
};

const actionToJson = (value) => {
  if (value.is_AddSubject) {
    return {
      type: 'AddSubject',
      s: dafnyStringToJs(value.dtor_s)
    };
  } else if (value.is_Grant) {
    return {
      type: 'Grant',
      s: dafnyStringToJs(value.dtor_s),
      cap: dafnyStringToJs(value.dtor_cap)
    };
  } else if (value.is_Delegate) {
    return {
      type: 'Delegate',
      from: dafnyStringToJs(value.dtor_from),
      to: dafnyStringToJs(value.dtor_to),
      cap: dafnyStringToJs(value.dtor_cap)
    };
  } else if (value.is_Revoke) {
    return {
      type: 'Revoke',
      eid: toNumber(value.dtor_eid)
    };
  }
  return { type: 'Unknown' };
};

const historyFromJson = (json) => {
  return DelegationAuthKernel.History.create_History(
    _dafny.Seq.of(...(json.past || []).map(x => modelFromJson(x))),
    modelFromJson(json.present),
    _dafny.Seq.of(...(json.future || []).map(x => modelFromJson(x)))
  );
};

const historyToJson = (value) => {
  return {
    past: seqToArray(value.dtor_past).map(x => modelToJson(x)),
    present: modelToJson(value.dtor_present),
    future: seqToArray(value.dtor_future).map(x => modelToJson(x))
  };
};

// ============================================================================
// API Wrapper
// ============================================================================

const App = {
  // Deleg constructors
  Deleg: (from, to, cap) => DelegationAuthDomain.Deleg.create_Deleg(_dafny.Seq.UnicodeFromString(from), _dafny.Seq.UnicodeFromString(to), _dafny.Seq.UnicodeFromString(cap)),

  // Action constructors
  AddSubject: (s) => DelegationAuthDomain.Action.create_AddSubject(_dafny.Seq.UnicodeFromString(s)),
  Grant: (s, cap) => DelegationAuthDomain.Action.create_Grant(_dafny.Seq.UnicodeFromString(s), _dafny.Seq.UnicodeFromString(cap)),
  Delegate: (from, to, cap) => DelegationAuthDomain.Action.create_Delegate(_dafny.Seq.UnicodeFromString(from), _dafny.Seq.UnicodeFromString(to), _dafny.Seq.UnicodeFromString(cap)),
  Revoke: (eid) => DelegationAuthDomain.Action.create_Revoke(new BigNumber(eid)),

  // Model accessors
  GetSubjects: (m) => Array.from(m.dtor_subjects.Elements).map(x => dafnyStringToJs(x)),
  GetGrants: (m) => Array.from(m.dtor_grants.Elements).map(x => [dafnyStringToJs(x[0]), dafnyStringToJs(x[1])]),
  GetDelegations: (m, key) => {
    const dafnyKey = new BigNumber(key);
    if (m.dtor_delegations.contains(dafnyKey)) {
      const val = m.dtor_delegations.get(dafnyKey);
      return delegToJson(val);
    }
    return null;
  },
  GetNextEdge: (m) => toNumber(m.dtor_nextEdge),

  // AppCore functions
  Init: () => DelegationAuthAppCore.__default.Init(),
  Dispatch: (h, a) => DelegationAuthAppCore.__default.Dispatch(h, a),
  Undo: (h) => DelegationAuthAppCore.__default.Undo(h),
  Redo: (h) => DelegationAuthAppCore.__default.Redo(h),
  Present: (h) => DelegationAuthAppCore.__default.Present(h),
  CanUndo: (h) => DelegationAuthAppCore.__default.CanUndo(h),
  CanRedo: (h) => DelegationAuthAppCore.__default.CanRedo(h),
  CheckCan: (m, s, cap) => DelegationAuthAppCore.__default.CheckCan(m, _dafny.Seq.UnicodeFromString(s), _dafny.Seq.UnicodeFromString(cap)),
  GetReachable: (m, cap) => DelegationAuthAppCore.__default.GetReachable(m, _dafny.Seq.UnicodeFromString(cap)),

  // Conversion functions
  delegToJson: delegToJson,
  delegFromJson: delegFromJson,
  modelToJson: modelToJson,
  modelFromJson: modelFromJson,
  actionToJson: actionToJson,
  actionFromJson: actionFromJson,
  historyToJson: historyToJson,
  historyFromJson: historyFromJson,
};

// Export internals for custom extensions
App._internal = { _dafny, DelegationAuthDomain, DelegationAuthKernel, DelegationAuthAppCore };

export default App;
