// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './DelegationAuth.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod: string) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, DelegationAuthDomain, DelegationAuthKernel, DelegationAuthAppCore };
`);

const { _dafny, DelegationAuthDomain, DelegationAuthKernel, DelegationAuthAppCore } = initDafny(require);

// ============================================================================
// Helpers
// ============================================================================

// deno-lint-ignore no-explicit-any
const seqToArray = (seq: any): any[] => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// deno-lint-ignore no-explicit-any
const toNumber = (bn: any): number => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};

// deno-lint-ignore no-explicit-any
const dafnyStringToJs = (seq: any): string => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};


// ============================================================================
// TypeScript Type Definitions (JSON representation)
// ============================================================================

export interface Deleg {
  from: string;
  to: string;
  cap: string;
}

export interface Model {
  subjects: string[];
  grants: [string, string][];
  delegations: Record<string, Deleg>;
  nextEdge: number;
}

export type Action =
  | { type: 'AddSubject'; s: string }
  | { type: 'Grant'; s: string; cap: string }
  | { type: 'Delegate'; from: string; to: string; cap: string }
  | { type: 'Revoke'; eid: number };

export interface History {
  past: Model[];
  present: Model;
  future: Model[];
}

// ============================================================================
// Dafny Runtime Types (actual Dafny runtime object shapes)
// ============================================================================

// Base Dafny runtime types
type DafnyInt = InstanceType<typeof BigNumber>;
interface DafnySeq<T = unknown> {
  readonly length: number;
  readonly [index: number]: T;
  toVerbatimString?(asLiteral: boolean): string;
  map<U>(fn: (x: T) => U): U[];
}
interface DafnySet<T = unknown> { readonly Elements: Iterable<T>; }
interface DafnyMap<K = unknown, V = unknown> {
  readonly Keys: DafnySet<K>;
  get(key: K): V;
  contains(key: K): boolean;
}
type DafnyTuple2<T0, T1> = readonly [T0, T1];

interface DafnyDeleg {
  readonly is_Deleg: true;
  readonly dtor_from: DafnySeq;
  readonly dtor_to: DafnySeq;
  readonly dtor_cap: DafnySeq;
}

interface DafnyModel {
  readonly is_Model: true;
  readonly dtor_subjects: DafnySet<DafnySeq>;
  readonly dtor_grants: DafnySet<DafnyTuple2<DafnySeq, DafnySeq>>;
  readonly dtor_delegations: DafnyMap<DafnyInt, DafnyDeleg>;
  readonly dtor_nextEdge: DafnyInt;
}

type DafnyAction = { readonly is_AddSubject: true; readonly is_Grant: false; readonly is_Delegate: false; readonly is_Revoke: false; readonly dtor_s: DafnySeq } | { readonly is_AddSubject: false; readonly is_Grant: true; readonly is_Delegate: false; readonly is_Revoke: false; readonly dtor_s: DafnySeq; readonly dtor_cap: DafnySeq } | { readonly is_AddSubject: false; readonly is_Grant: false; readonly is_Delegate: true; readonly is_Revoke: false; readonly dtor_from: DafnySeq; readonly dtor_to: DafnySeq; readonly dtor_cap: DafnySeq } | { readonly is_AddSubject: false; readonly is_Grant: false; readonly is_Delegate: false; readonly is_Revoke: true; readonly dtor_eid: DafnyInt };

interface DafnyHistory {
  readonly is_History: true;
  readonly dtor_past: DafnySeq<DafnyModel>;
  readonly dtor_present: DafnyModel;
  readonly dtor_future: DafnySeq<DafnyModel>;
}

// ============================================================================
// Datatype Conversions
// ============================================================================

// deno-lint-ignore no-explicit-any
const delegFromJson = (json: any): DafnyDeleg => {
  return DelegationAuthDomain.Deleg.create_Deleg(
    _dafny.Seq.UnicodeFromString(json.from),
    _dafny.Seq.UnicodeFromString(json.to),
    _dafny.Seq.UnicodeFromString(json.cap)
  );
};

// deno-lint-ignore no-explicit-any
const delegToJson = (value: any): Deleg => {
  return {
    from: dafnyStringToJs(value.dtor_from),
    to: dafnyStringToJs(value.dtor_to),
    cap: dafnyStringToJs(value.dtor_cap)
  };
};

// deno-lint-ignore no-explicit-any
const modelFromJson = (json: any): DafnyModel => {
  let __delegations = _dafny.Map.Empty;
  for (const [k, v] of (Object.entries(json.delegations || {}) as [string, any][])) {
    const key = new BigNumber(k);
    const val = delegFromJson(v);
    __delegations = __delegations.update(key, val);
  }
  return DelegationAuthDomain.Model.create_Model(
    _dafny.Set.fromElements(...(json.subjects || []).map((x: any) => _dafny.Seq.UnicodeFromString(x))),
    _dafny.Set.fromElements(...(json.grants || []).map((x: any) => _dafny.Tuple.create_2(_dafny.Seq.UnicodeFromString(x[0]), _dafny.Seq.UnicodeFromString(x[1])))),
    __delegations,
    new BigNumber(json.nextEdge)
  );
};

// deno-lint-ignore no-explicit-any
const modelToJson = (value: any): Model => {
  const __delegationsJson: Record<string, any> = {};
  if (value.dtor_delegations && value.dtor_delegations.Keys) {
    for (const k of value.dtor_delegations.Keys.Elements) {
      const v = value.dtor_delegations.get(k);
      __delegationsJson[toNumber(k)] = delegToJson(v);
    }
  }
  return {
    subjects: Array.from(value.dtor_subjects.Elements).map((x: any) => dafnyStringToJs(x)),
    grants: Array.from(value.dtor_grants.Elements).map((x: any) => [dafnyStringToJs(x[0]), dafnyStringToJs(x[1])]),
    delegations: __delegationsJson,
    nextEdge: toNumber(value.dtor_nextEdge)
  };
};

// deno-lint-ignore no-explicit-any
const actionFromJson = (json: any): DafnyAction => {
  switch (json.type) {
    case 'AddSubject': {
      return DelegationAuthDomain.Action.create_AddSubject(
        _dafny.Seq.UnicodeFromString(json.s)
      );
    }
    case 'Grant': {
      return DelegationAuthDomain.Action.create_Grant(
        _dafny.Seq.UnicodeFromString(json.s),
        _dafny.Seq.UnicodeFromString(json.cap)
      );
    }
    case 'Delegate': {
      return DelegationAuthDomain.Action.create_Delegate(
        _dafny.Seq.UnicodeFromString(json.from),
        _dafny.Seq.UnicodeFromString(json.to),
        _dafny.Seq.UnicodeFromString(json.cap)
      );
    }
    case 'Revoke': {
      return DelegationAuthDomain.Action.create_Revoke(
        new BigNumber(json.eid)
      );
    }
    default:
      throw new Error(`Unknown Action type: ${json.type}`);
  }
};

// deno-lint-ignore no-explicit-any
const actionToJson = (value: any): Action => {
  if (value.is_AddSubject) {
    return {
      type: 'AddSubject',
      s: dafnyStringToJs(value.dtor_s)
    };
  } else if (value.is_Grant) {
    return {
      type: 'Grant',
      s: dafnyStringToJs(value.dtor_s),
      cap: dafnyStringToJs(value.dtor_cap)
    };
  } else if (value.is_Delegate) {
    return {
      type: 'Delegate',
      from: dafnyStringToJs(value.dtor_from),
      to: dafnyStringToJs(value.dtor_to),
      cap: dafnyStringToJs(value.dtor_cap)
    };
  } else if (value.is_Revoke) {
    return {
      type: 'Revoke',
      eid: toNumber(value.dtor_eid)
    };
  }
  throw new Error('Unknown Action variant');
};

// deno-lint-ignore no-explicit-any
const historyFromJson = (json: any): DafnyHistory => {
  return DelegationAuthKernel.History.create_History(
    _dafny.Seq.of(...(json.past || []).map((x: any) => modelFromJson(x))),
    modelFromJson(json.present),
    _dafny.Seq.of(...(json.future || []).map((x: any) => modelFromJson(x)))
  );
};

// deno-lint-ignore no-explicit-any
const historyToJson = (value: any): History => {
  return {
    past: seqToArray(value.dtor_past).map((x: any) => modelToJson(x)),
    present: modelToJson(value.dtor_present),
    future: seqToArray(value.dtor_future).map((x: any) => modelToJson(x))
  };
};

// ============================================================================
// API Wrapper
// ============================================================================

interface AppInternal { _dafny: unknown; DelegationAuthDomain: unknown; DelegationAuthKernel: unknown; DelegationAuthAppCore: unknown; }

const App = {
  // Deleg constructors
  Deleg: (from: string, to: string, cap: string) => DelegationAuthDomain.Deleg.create_Deleg(_dafny.Seq.UnicodeFromString(from), _dafny.Seq.UnicodeFromString(to), _dafny.Seq.UnicodeFromString(cap)),

  // Action constructors
  AddSubject: (s: string) => DelegationAuthDomain.Action.create_AddSubject(_dafny.Seq.UnicodeFromString(s)),
  Grant: (s: string, cap: string) => DelegationAuthDomain.Action.create_Grant(_dafny.Seq.UnicodeFromString(s), _dafny.Seq.UnicodeFromString(cap)),
  Delegate: (from: string, to: string, cap: string) => DelegationAuthDomain.Action.create_Delegate(_dafny.Seq.UnicodeFromString(from), _dafny.Seq.UnicodeFromString(to), _dafny.Seq.UnicodeFromString(cap)),
  Revoke: (eid: number) => DelegationAuthDomain.Action.create_Revoke(new BigNumber(eid)),

  // Model accessors
  GetSubjects: (m: DafnyModel) => Array.from(m.dtor_subjects.Elements).map((x: any) => dafnyStringToJs(x)),
  GetGrants: (m: DafnyModel) => Array.from(m.dtor_grants.Elements).map((x: any) => [dafnyStringToJs(x[0]), dafnyStringToJs(x[1])]),
  GetDelegations: (m: DafnyModel, key: number) => {
    const dafnyKey = new BigNumber(key);
    if (m.dtor_delegations.contains(dafnyKey)) {
      const val = m.dtor_delegations.get(dafnyKey);
      return delegToJson(val);
    }
    return null;
  },
  GetNextEdge: (m: DafnyModel) => toNumber(m.dtor_nextEdge),

  // AppCore functions
  Init: (): DafnyHistory => DelegationAuthAppCore.__default.Init(),
  Dispatch: (h: DafnyHistory, a: DafnyAction): DafnyHistory => DelegationAuthAppCore.__default.Dispatch(h, a),
  Undo: (h: DafnyHistory): DafnyHistory => DelegationAuthAppCore.__default.Undo(h),
  Redo: (h: DafnyHistory): DafnyHistory => DelegationAuthAppCore.__default.Redo(h),
  Present: (h: DafnyHistory): DafnyModel => DelegationAuthAppCore.__default.Present(h),
  CanUndo: (h: DafnyHistory): boolean => DelegationAuthAppCore.__default.CanUndo(h),
  CanRedo: (h: DafnyHistory): boolean => DelegationAuthAppCore.__default.CanRedo(h),
  CheckCan: (m: DafnyModel, s: string, cap: string): boolean => DelegationAuthAppCore.__default.CheckCan(m, _dafny.Seq.UnicodeFromString(s), _dafny.Seq.UnicodeFromString(cap)),
  GetReachable: (m: DafnyModel, cap: string): DafnySet<DafnySeq> => DelegationAuthAppCore.__default.GetReachable(m, _dafny.Seq.UnicodeFromString(cap)),

  // Conversion functions
  delegToJson,
  delegFromJson,
  modelToJson,
  modelFromJson,
  actionToJson,
  actionFromJson,
  historyToJson,
  historyFromJson,

  // Internal modules for custom extensions
  _internal: { _dafny, DelegationAuthDomain, DelegationAuthKernel, DelegationAuthAppCore } as AppInternal,
};

export default App;
