// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './Validation.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod: string) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, Validation };
`);

const { _dafny, Validation } = initDafny(require);

// ============================================================================
// Helpers
// ============================================================================

// deno-lint-ignore no-explicit-any
const seqToArray = (seq: any): any[] => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// deno-lint-ignore no-explicit-any
const toNumber = (bn: any): number => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};

// deno-lint-ignore no-explicit-any
const dafnyStringToJs = (seq: any): string => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};


// ============================================================================
// TypeScript Type Definitions (JSON representation)
// ============================================================================

export type Option<T> =
  | { type: 'None' }
  | { type: 'Some'; value: T };

export type Constraint =
  | { type: 'Required' }
  | { type: 'MinLength'; min: number }
  | { type: 'MaxLength'; max: number }
  | { type: 'OneOf'; allowed: string[] }
  | { type: 'DependsOn'; field: string; triggerValue: string };

export interface Rule {
  field: string;
  constraints: Constraint[];
}

export interface ValidationError {
  field: string;
  message: string;
}

// ============================================================================
// Dafny Runtime Types (actual Dafny runtime object shapes)
// ============================================================================

// Base Dafny runtime types
type DafnyInt = InstanceType<typeof BigNumber>;
interface DafnySeq<T = unknown> {
  readonly length: number;
  readonly [index: number]: T;
  toVerbatimString?(asLiteral: boolean): string;
  map<U>(fn: (x: T) => U): U[];
}
interface DafnySet<T = unknown> { readonly Elements: Iterable<T>; }
interface DafnyMap<K = unknown, V = unknown> {
  readonly Keys: DafnySet<K>;
  get(key: K): V;
  contains(key: K): boolean;
}

type DafnyOption<T> = { readonly is_None: true; readonly is_Some: false } | { readonly is_None: false; readonly is_Some: true; readonly dtor_value: T };

type DafnyConstraint = { readonly is_Required: true; readonly is_MinLength: false; readonly is_MaxLength: false; readonly is_OneOf: false; readonly is_DependsOn: false } | { readonly is_Required: false; readonly is_MinLength: true; readonly is_MaxLength: false; readonly is_OneOf: false; readonly is_DependsOn: false; readonly dtor_min: DafnyInt } | { readonly is_Required: false; readonly is_MinLength: false; readonly is_MaxLength: true; readonly is_OneOf: false; readonly is_DependsOn: false; readonly dtor_max: DafnyInt } | { readonly is_Required: false; readonly is_MinLength: false; readonly is_MaxLength: false; readonly is_OneOf: true; readonly is_DependsOn: false; readonly dtor_allowed: DafnySeq<DafnySeq> } | { readonly is_Required: false; readonly is_MinLength: false; readonly is_MaxLength: false; readonly is_OneOf: false; readonly is_DependsOn: true; readonly dtor_field: DafnySeq; readonly dtor_triggerValue: DafnySeq };

interface DafnyRule {
  readonly is_Rule: true;
  readonly dtor_field: DafnySeq;
  readonly dtor_constraints: DafnySeq<DafnyConstraint>;
}

interface DafnyValidationError {
  readonly is_ValidationError: true;
  readonly dtor_field: DafnySeq;
  readonly dtor_message: DafnySeq;
}

// ============================================================================
// Datatype Conversions
// ============================================================================

// deno-lint-ignore no-explicit-any
const optionFromJson = <T>(json: any, T_fromJson: (x: any) => T): DafnyOption<T> => {
  // Handle null/undefined (DB compatibility with --null-options)
  if (json === null || json === undefined) {
    return Validation.Option.create_None();
  }
  // Handle raw values without type tag (DB stores unwrapped Some values)
  if (!json.type) {
    return Validation.Option.create_Some(T_fromJson(json));
  }
  switch (json.type) {
    case 'None': {
      return Validation.Option.create_None();
    }
    case 'Some': {
      return Validation.Option.create_Some(
        T_fromJson(json.value)
      );
    }
    default:
      throw new Error(`Unknown Option type: ${json.type}`);
  }
};

// deno-lint-ignore no-explicit-any
const optionToJson = <T>(value: any, T_toJson: (x: any) => any): Option<T> => {
  if (value.is_None) {
    return { type: 'None' };
  } else if (value.is_Some) {
    return {
      type: 'Some',
      value: T_toJson(value.dtor_value)
    };
  }
  throw new Error('Unknown Option variant');
};

// deno-lint-ignore no-explicit-any
const constraintFromJson = (json: any): DafnyConstraint => {
  switch (json.type) {
    case 'Required': {
      return Validation.Constraint.create_Required();
    }
    case 'MinLength': {
      return Validation.Constraint.create_MinLength(
        new BigNumber(json.min)
      );
    }
    case 'MaxLength': {
      return Validation.Constraint.create_MaxLength(
        new BigNumber(json.max)
      );
    }
    case 'OneOf': {
      return Validation.Constraint.create_OneOf(
        _dafny.Seq.of(...(json.allowed || []).map((x: any) => _dafny.Seq.UnicodeFromString(x)))
      );
    }
    case 'DependsOn': {
      return Validation.Constraint.create_DependsOn(
        _dafny.Seq.UnicodeFromString(json.field),
        _dafny.Seq.UnicodeFromString(json.triggerValue)
      );
    }
    default:
      throw new Error(`Unknown Constraint type: ${json.type}`);
  }
};

// deno-lint-ignore no-explicit-any
const constraintToJson = (value: any): Constraint => {
  if (value.is_Required) {
    return { type: 'Required' };
  } else if (value.is_MinLength) {
    return {
      type: 'MinLength',
      min: toNumber(value.dtor_min)
    };
  } else if (value.is_MaxLength) {
    return {
      type: 'MaxLength',
      max: toNumber(value.dtor_max)
    };
  } else if (value.is_OneOf) {
    return {
      type: 'OneOf',
      allowed: seqToArray(value.dtor_allowed).map((x: any) => dafnyStringToJs(x))
    };
  } else if (value.is_DependsOn) {
    return {
      type: 'DependsOn',
      field: dafnyStringToJs(value.dtor_field),
      triggerValue: dafnyStringToJs(value.dtor_triggerValue)
    };
  }
  throw new Error('Unknown Constraint variant');
};

// deno-lint-ignore no-explicit-any
const ruleFromJson = (json: any): DafnyRule => {
  return Validation.Rule.create_Rule(
    _dafny.Seq.UnicodeFromString(json.field),
    _dafny.Seq.of(...(json.constraints || []).map((x: any) => constraintFromJson(x)))
  );
};

// deno-lint-ignore no-explicit-any
const ruleToJson = (value: any): Rule => {
  return {
    field: dafnyStringToJs(value.dtor_field),
    constraints: seqToArray(value.dtor_constraints).map((x: any) => constraintToJson(x))
  };
};

// deno-lint-ignore no-explicit-any
const validationerrorFromJson = (json: any): DafnyValidationError => {
  return Validation.ValidationError.create_ValidationError(
    _dafny.Seq.UnicodeFromString(json.field),
    _dafny.Seq.UnicodeFromString(json.message)
  );
};

// deno-lint-ignore no-explicit-any
const validationerrorToJson = (value: any): ValidationError => {
  return {
    field: dafnyStringToJs(value.dtor_field),
    message: dafnyStringToJs(value.dtor_message)
  };
};

// ============================================================================
// Null-Option Preprocessing (for DB compatibility)
// ============================================================================

// Convert null to { type: 'None' } for Option fields
// deno-lint-ignore no-explicit-any
const fixOption = (val: any): any => {
  if (val === null || val === undefined) return { type: 'None' };
  if (val && val.type) return val; // Already in correct format
  return { type: 'Some', value: val };
};


// ============================================================================
// API Wrapper
// ============================================================================

interface AppInternal { _dafny: unknown; Validation: unknown; }

const App = {
  // Option constructors
  None: () => Validation.Option.create_None(),
  Some: (value: unknown) => Validation.Option.create_Some(value),

  // Constraint constructors
  Required: () => Validation.Constraint.create_Required(),
  MinLength: (min: number) => Validation.Constraint.create_MinLength(new BigNumber(min)),
  MaxLength: (max: number) => Validation.Constraint.create_MaxLength(new BigNumber(max)),
  OneOf: (allowed: string[]) => Validation.Constraint.create_OneOf(_dafny.Seq.of(...(allowed || []).map((x: any) => _dafny.Seq.UnicodeFromString(x)))),
  DependsOn: (field: string, triggerValue: string) => Validation.Constraint.create_DependsOn(_dafny.Seq.UnicodeFromString(field), _dafny.Seq.UnicodeFromString(triggerValue)),

  // Rule constructors
  Rule: (field: string, constraints: Constraint[]) => Validation.Rule.create_Rule(_dafny.Seq.UnicodeFromString(field), _dafny.Seq.of(...(constraints || []).map((x: any) => constraintFromJson(x)))),

  // ValidationError constructors
  ValidationError: (field: string, message: string) => Validation.ValidationError.create_ValidationError(_dafny.Seq.UnicodeFromString(field), _dafny.Seq.UnicodeFromString(message)),

  // AppCore functions
  SatisfiesConstraint: (form: Record<string, Option<string>>, fieldName: string, value: Option<string>, c: Constraint): boolean => Validation.__default.SatisfiesConstraint(((obj) => { let m = _dafny.Map.Empty; for (const [k, v] of Object.entries(obj || {})) { m = m.update(_dafny.Seq.UnicodeFromString(k), optionFromJson(v, (x: any) => _dafny.Seq.UnicodeFromString(x))); } return m; })(form), _dafny.Seq.UnicodeFromString(fieldName), optionFromJson(value, (x: any) => _dafny.Seq.UnicodeFromString(x)), constraintFromJson(c)),
  SatisfiesRule: (form: Record<string, Option<string>>, rule: Rule): boolean => Validation.__default.SatisfiesRule(((obj) => { let m = _dafny.Map.Empty; for (const [k, v] of Object.entries(obj || {})) { m = m.update(_dafny.Seq.UnicodeFromString(k), optionFromJson(v, (x: any) => _dafny.Seq.UnicodeFromString(x))); } return m; })(form), ruleFromJson(rule)),
  IsValid: (form: Record<string, Option<string>>, rules: Rule[]): boolean => Validation.__default.IsValid(((obj) => { let m = _dafny.Map.Empty; for (const [k, v] of Object.entries(obj || {})) { m = m.update(_dafny.Seq.UnicodeFromString(k), optionFromJson(v, (x: any) => _dafny.Seq.UnicodeFromString(x))); } return m; })(form), _dafny.Seq.of(...(rules || []).map((x: any) => ruleFromJson(x)))),
  ErrorsForRule: (form: Record<string, Option<string>>, rule: Rule): ValidationError[] => seqToArray(Validation.__default.ErrorsForRule(((obj) => { let m = _dafny.Map.Empty; for (const [k, v] of Object.entries(obj || {})) { m = m.update(_dafny.Seq.UnicodeFromString(k), optionFromJson(v, (x: any) => _dafny.Seq.UnicodeFromString(x))); } return m; })(form), ruleFromJson(rule))).map(x => validationerrorToJson(x)),
  ErrorsForConstraints: (form: Record<string, Option<string>>, fieldName: string, value: Option<string>, constraints: Constraint[]): ValidationError[] => seqToArray(Validation.__default.ErrorsForConstraints(((obj) => { let m = _dafny.Map.Empty; for (const [k, v] of Object.entries(obj || {})) { m = m.update(_dafny.Seq.UnicodeFromString(k), optionFromJson(v, (x: any) => _dafny.Seq.UnicodeFromString(x))); } return m; })(form), _dafny.Seq.UnicodeFromString(fieldName), optionFromJson(value, (x: any) => _dafny.Seq.UnicodeFromString(x)), _dafny.Seq.of(...(constraints || []).map((x: any) => constraintFromJson(x))))).map(x => validationerrorToJson(x)),
  ConstraintMessage: (c: Constraint): string => dafnyStringToJs(Validation.__default.ConstraintMessage(constraintFromJson(c))),
  Validate: (form: Record<string, Option<string>>, rules: Rule[]): ValidationError[] => seqToArray(Validation.__default.Validate(((obj) => { let m = _dafny.Map.Empty; for (const [k, v] of Object.entries(obj || {})) { m = m.update(_dafny.Seq.UnicodeFromString(k), optionFromJson(v, (x: any) => _dafny.Seq.UnicodeFromString(x))); } return m; })(form), _dafny.Seq.of(...(rules || []).map((x: any) => ruleFromJson(x))))).map(x => validationerrorToJson(x)),

  // Conversion functions
  optionToJson,
  optionFromJson,
  constraintToJson,
  constraintFromJson,
  ruleToJson,
  ruleFromJson,
  validationerrorToJson,
  validationerrorFromJson,

  // Internal modules for custom extensions
  _internal: { _dafny, Validation } as AppInternal,
};

export default App;
