// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './Workflow.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod: string) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, Workflow };
`);

const { _dafny, Workflow } = initDafny(require);

// ============================================================================
// Helpers
// ============================================================================

// deno-lint-ignore no-explicit-any
const seqToArray = (seq: any): any[] => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// deno-lint-ignore no-explicit-any
const dafnyStringToJs = (seq: any): string => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};


// ============================================================================
// TypeScript Type Definitions (JSON representation)
// ============================================================================

export type State = 'Draft' | 'Submitted' | 'InReview' | 'Approved' | 'Rejected' | 'Published';

export type Transition = 'Submit' | 'BeginReview' | 'Approve' | 'Reject' | 'Publish' | 'Revise';

export interface Doc {
  state: State;
  reviewers: string[];
}

export type TransitionResult =
  | { type: 'OK' }
  | { type: 'Blocked'; reason: string };

// ============================================================================
// Dafny Runtime Types (actual Dafny runtime object shapes)
// ============================================================================

// Base Dafny runtime types
interface DafnySeq<T = unknown> {
  readonly length: number;
  readonly [index: number]: T;
  toVerbatimString?(asLiteral: boolean): string;
  map<U>(fn: (x: T) => U): U[];
}

type DafnyState = { readonly is_Draft: true; readonly is_Submitted: false; readonly is_InReview: false; readonly is_Approved: false; readonly is_Rejected: false; readonly is_Published: false } | { readonly is_Draft: false; readonly is_Submitted: true; readonly is_InReview: false; readonly is_Approved: false; readonly is_Rejected: false; readonly is_Published: false } | { readonly is_Draft: false; readonly is_Submitted: false; readonly is_InReview: true; readonly is_Approved: false; readonly is_Rejected: false; readonly is_Published: false } | { readonly is_Draft: false; readonly is_Submitted: false; readonly is_InReview: false; readonly is_Approved: true; readonly is_Rejected: false; readonly is_Published: false } | { readonly is_Draft: false; readonly is_Submitted: false; readonly is_InReview: false; readonly is_Approved: false; readonly is_Rejected: true; readonly is_Published: false } | { readonly is_Draft: false; readonly is_Submitted: false; readonly is_InReview: false; readonly is_Approved: false; readonly is_Rejected: false; readonly is_Published: true };

type DafnyTransition = { readonly is_Submit: true; readonly is_BeginReview: false; readonly is_Approve: false; readonly is_Reject: false; readonly is_Publish: false; readonly is_Revise: false } | { readonly is_Submit: false; readonly is_BeginReview: true; readonly is_Approve: false; readonly is_Reject: false; readonly is_Publish: false; readonly is_Revise: false } | { readonly is_Submit: false; readonly is_BeginReview: false; readonly is_Approve: true; readonly is_Reject: false; readonly is_Publish: false; readonly is_Revise: false } | { readonly is_Submit: false; readonly is_BeginReview: false; readonly is_Approve: false; readonly is_Reject: true; readonly is_Publish: false; readonly is_Revise: false } | { readonly is_Submit: false; readonly is_BeginReview: false; readonly is_Approve: false; readonly is_Reject: false; readonly is_Publish: true; readonly is_Revise: false } | { readonly is_Submit: false; readonly is_BeginReview: false; readonly is_Approve: false; readonly is_Reject: false; readonly is_Publish: false; readonly is_Revise: true };

interface DafnyDoc {
  readonly is_Doc: true;
  readonly dtor_state: DafnyState;
  readonly dtor_reviewers: DafnySeq<DafnySeq>;
}

type DafnyTransitionResult = { readonly is_OK: true; readonly is_Blocked: false } | { readonly is_OK: false; readonly is_Blocked: true; readonly dtor_reason: DafnySeq };

// ============================================================================
// Datatype Conversions
// ============================================================================

// deno-lint-ignore no-explicit-any
const stateFromJson = (json: any): DafnyState => {
  switch (json) {
    case 'Draft':
      return Workflow.State.create_Draft();
    case 'Submitted':
      return Workflow.State.create_Submitted();
    case 'InReview':
      return Workflow.State.create_InReview();
    case 'Approved':
      return Workflow.State.create_Approved();
    case 'Rejected':
      return Workflow.State.create_Rejected();
    case 'Published':
      return Workflow.State.create_Published();
    default:
      throw new Error(`Unknown State: ${json}`);
  }
};

// deno-lint-ignore no-explicit-any
const stateToJson = (value: any): State => {
  if (value.is_Draft) {
    return 'Draft';
  } else if (value.is_Submitted) {
    return 'Submitted';
  } else if (value.is_InReview) {
    return 'InReview';
  } else if (value.is_Approved) {
    return 'Approved';
  } else if (value.is_Rejected) {
    return 'Rejected';
  } else if (value.is_Published) {
    return 'Published';
  }
  throw new Error('Unknown State variant');
};

// deno-lint-ignore no-explicit-any
const transitionFromJson = (json: any): DafnyTransition => {
  switch (json) {
    case 'Submit':
      return Workflow.Transition.create_Submit();
    case 'BeginReview':
      return Workflow.Transition.create_BeginReview();
    case 'Approve':
      return Workflow.Transition.create_Approve();
    case 'Reject':
      return Workflow.Transition.create_Reject();
    case 'Publish':
      return Workflow.Transition.create_Publish();
    case 'Revise':
      return Workflow.Transition.create_Revise();
    default:
      throw new Error(`Unknown Transition: ${json}`);
  }
};

// deno-lint-ignore no-explicit-any
const transitionToJson = (value: any): Transition => {
  if (value.is_Submit) {
    return 'Submit';
  } else if (value.is_BeginReview) {
    return 'BeginReview';
  } else if (value.is_Approve) {
    return 'Approve';
  } else if (value.is_Reject) {
    return 'Reject';
  } else if (value.is_Publish) {
    return 'Publish';
  } else if (value.is_Revise) {
    return 'Revise';
  }
  throw new Error('Unknown Transition variant');
};

// deno-lint-ignore no-explicit-any
const docFromJson = (json: any): DafnyDoc => {
  return Workflow.Doc.create_Doc(
    stateFromJson(json.state),
    _dafny.Seq.of(...(json.reviewers || []).map((x: any) => _dafny.Seq.UnicodeFromString(x)))
  );
};

// deno-lint-ignore no-explicit-any
const docToJson = (value: any): Doc => {
  return {
    state: stateToJson(value.dtor_state),
    reviewers: seqToArray(value.dtor_reviewers).map((x: any) => dafnyStringToJs(x))
  };
};

// deno-lint-ignore no-explicit-any
const transitionresultFromJson = (json: any): DafnyTransitionResult => {
  switch (json.type) {
    case 'OK': {
      return Workflow.TransitionResult.create_OK();
    }
    case 'Blocked': {
      return Workflow.TransitionResult.create_Blocked(
        _dafny.Seq.UnicodeFromString(json.reason)
      );
    }
    default:
      throw new Error(`Unknown TransitionResult type: ${json.type}`);
  }
};

// deno-lint-ignore no-explicit-any
const transitionresultToJson = (value: any): TransitionResult => {
  if (value.is_OK) {
    return { type: 'OK' };
  } else if (value.is_Blocked) {
    return {
      type: 'Blocked',
      reason: dafnyStringToJs(value.dtor_reason)
    };
  }
  throw new Error('Unknown TransitionResult variant');
};

// ============================================================================
// API Wrapper
// ============================================================================

interface AppInternal { _dafny: unknown; Workflow: unknown; }

const App = {
  // State constructors
  Draft: () => Workflow.State.create_Draft(),
  Submitted: () => Workflow.State.create_Submitted(),
  InReview: () => Workflow.State.create_InReview(),
  Approved: () => Workflow.State.create_Approved(),
  Rejected: () => Workflow.State.create_Rejected(),
  Published: () => Workflow.State.create_Published(),

  // Transition constructors
  Submit: () => Workflow.Transition.create_Submit(),
  BeginReview: () => Workflow.Transition.create_BeginReview(),
  Approve: () => Workflow.Transition.create_Approve(),
  Reject: () => Workflow.Transition.create_Reject(),
  Publish: () => Workflow.Transition.create_Publish(),
  Revise: () => Workflow.Transition.create_Revise(),

  // Doc constructors
  Doc: (state: State, reviewers: string[]) => Workflow.Doc.create_Doc(stateFromJson(state), _dafny.Seq.of(...(reviewers || []).map((x: any) => _dafny.Seq.UnicodeFromString(x)))),

  // TransitionResult constructors
  OK: () => Workflow.TransitionResult.create_OK(),
  Blocked: (reason: string) => Workflow.TransitionResult.create_Blocked(_dafny.Seq.UnicodeFromString(reason)),

  // AppCore functions
  ValidTransition: (from: State, t: Transition): boolean => Workflow.__default.ValidTransition(stateFromJson(from), transitionFromJson(t)),
  TargetState: (t: Transition): State => stateToJson((Workflow.__default.TargetState(transitionFromJson(t)))),
  DocInv: (doc: Doc): boolean => Workflow.__default.DocInv(docFromJson(doc)),
  TransitionGuard: (doc: Doc, t: Transition): boolean => Workflow.__default.TransitionGuard(docFromJson(doc), transitionFromJson(t)),
  IsTerminal: (s: State): boolean => Workflow.__default.IsTerminal(stateFromJson(s)),
  CanTransition: (doc: Doc, t: Transition): boolean => Workflow.__default.CanTransition(docFromJson(doc), transitionFromJson(t)),
  TryTransition: (doc: Doc, t: Transition): TransitionResult => transitionresultToJson((Workflow.__default.TryTransition(docFromJson(doc), transitionFromJson(t)))),
  StateName: (s: State): string => dafnyStringToJs(Workflow.__default.StateName(stateFromJson(s))),
  Step: (doc: Doc, t: Transition): Doc => docToJson((Workflow.__default.Step(docFromJson(doc), transitionFromJson(t)))),
  AddReviewer: (doc: Doc, reviewer: string): Doc => docToJson((Workflow.__default.AddReviewer(docFromJson(doc), _dafny.Seq.UnicodeFromString(reviewer)))),
  Init: (): Doc => docToJson((Workflow.__default.Init())),

  // Conversion functions
  stateToJson,
  stateFromJson,
  transitionToJson,
  transitionFromJson,
  docToJson,
  docFromJson,
  transitionresultToJson,
  transitionresultFromJson,

  // Internal modules for custom extensions
  _internal: { _dafny, Workflow } as AppInternal,
};

export default App;
