// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './Kanban.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, KanbanDomain, KanbanKernel, KanbanAppCore };
`);

const { _dafny, KanbanDomain, KanbanKernel, KanbanAppCore } = initDafny(require);


// ============================================================================
// Helpers
// ============================================================================

// Convert Dafny seq to JS array
const seqToArray = (seq) => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// Convert BigNumber to JS number
const toNumber = (bn) => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};

// Convert Dafny string to JS string
const dafnyStringToJs = (seq) => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};

// ============================================================================
// Datatype Conversions
// ============================================================================

const cardFromJson = (json) => {
  return KanbanDomain.Card.create_Card(
    _dafny.Seq.UnicodeFromString(json.title)
  );
};

const cardToJson = (value) => {
  return {
    title: dafnyStringToJs(value.dtor_title)
  };
};

const modelFromJson = (json) => {
  let __lanes = _dafny.Map.Empty;
  for (const [k, v] of Object.entries(json.lanes || {})) {
    const key = _dafny.Seq.UnicodeFromString(k);
    const val = _dafny.Seq.of(...(v || []).map(x => new BigNumber(x)));
    __lanes = __lanes.update(key, val);
  }
  let __wip = _dafny.Map.Empty;
  for (const [k, v] of Object.entries(json.wip || {})) {
    const key = _dafny.Seq.UnicodeFromString(k);
    const val = new BigNumber(v);
    __wip = __wip.update(key, val);
  }
  let __cards = _dafny.Map.Empty;
  for (const [k, v] of Object.entries(json.cards || {})) {
    const key = new BigNumber(k);
    const val = cardFromJson(v);
    __cards = __cards.update(key, val);
  }
  return KanbanDomain.Model.create_Model(
    _dafny.Seq.of(...(json.cols || []).map(x => _dafny.Seq.UnicodeFromString(x))),
    __lanes,
    __wip,
    __cards,
    new BigNumber(json.nextId)
  );
};

const modelToJson = (value) => {
  const __lanesJson = {};
  if (value.dtor_lanes && value.dtor_lanes.Keys) {
    for (const k of value.dtor_lanes.Keys.Elements) {
      const v = value.dtor_lanes.get(k);
      __lanesJson[dafnyStringToJs(k)] = seqToArray(v).map(x => toNumber(x));
    }
  }
  const __wipJson = {};
  if (value.dtor_wip && value.dtor_wip.Keys) {
    for (const k of value.dtor_wip.Keys.Elements) {
      const v = value.dtor_wip.get(k);
      __wipJson[dafnyStringToJs(k)] = toNumber(v);
    }
  }
  const __cardsJson = {};
  if (value.dtor_cards && value.dtor_cards.Keys) {
    for (const k of value.dtor_cards.Keys.Elements) {
      const v = value.dtor_cards.get(k);
      __cardsJson[toNumber(k)] = cardToJson(v);
    }
  }
  return {
    cols: seqToArray(value.dtor_cols).map(x => dafnyStringToJs(x)),
    lanes: __lanesJson,
    wip: __wipJson,
    cards: __cardsJson,
    nextId: toNumber(value.dtor_nextId)
  };
};

const actionFromJson = (json) => {
  switch (json.type) {
    case 'AddColumn': {
      return KanbanDomain.Action.create_AddColumn(
        _dafny.Seq.UnicodeFromString(json.col),
        new BigNumber(json.limit)
      );
    }
    case 'SetWip': {
      return KanbanDomain.Action.create_SetWip(
        _dafny.Seq.UnicodeFromString(json.col),
        new BigNumber(json.limit)
      );
    }
    case 'AddCard': {
      return KanbanDomain.Action.create_AddCard(
        _dafny.Seq.UnicodeFromString(json.col),
        _dafny.Seq.UnicodeFromString(json.title)
      );
    }
    case 'MoveCard': {
      return KanbanDomain.Action.create_MoveCard(
        new BigNumber(json.id),
        _dafny.Seq.UnicodeFromString(json.toCol),
        new BigNumber(json.pos)
      );
    }
    default:
      throw new Error(`Unknown Action type: ${json.type}`);
  }
};

const actionToJson = (value) => {
  if (value.is_AddColumn) {
    return {
      type: 'AddColumn',
      col: dafnyStringToJs(value.dtor_col),
      limit: toNumber(value.dtor_limit)
    };
  } else if (value.is_SetWip) {
    return {
      type: 'SetWip',
      col: dafnyStringToJs(value.dtor_col),
      limit: toNumber(value.dtor_limit)
    };
  } else if (value.is_AddCard) {
    return {
      type: 'AddCard',
      col: dafnyStringToJs(value.dtor_col),
      title: dafnyStringToJs(value.dtor_title)
    };
  } else if (value.is_MoveCard) {
    return {
      type: 'MoveCard',
      id: toNumber(value.dtor_id),
      toCol: dafnyStringToJs(value.dtor_toCol),
      pos: toNumber(value.dtor_pos)
    };
  }
  return { type: 'Unknown' };
};

const historyFromJson = (json) => {
  return KanbanKernel.History.create_History(
    _dafny.Seq.of(...(json.past || []).map(x => modelFromJson(x))),
    modelFromJson(json.present),
    _dafny.Seq.of(...(json.future || []).map(x => modelFromJson(x)))
  );
};

const historyToJson = (value) => {
  return {
    past: seqToArray(value.dtor_past).map(x => modelToJson(x)),
    present: modelToJson(value.dtor_present),
    future: seqToArray(value.dtor_future).map(x => modelToJson(x))
  };
};

// ============================================================================
// API Wrapper
// ============================================================================

const App = {
  // Card constructors
  Card: (title) => KanbanDomain.Card.create_Card(_dafny.Seq.UnicodeFromString(title)),

  // Action constructors
  AddColumn: (col, limit) => KanbanDomain.Action.create_AddColumn(_dafny.Seq.UnicodeFromString(col), new BigNumber(limit)),
  SetWip: (col, limit) => KanbanDomain.Action.create_SetWip(_dafny.Seq.UnicodeFromString(col), new BigNumber(limit)),
  AddCard: (col, title) => KanbanDomain.Action.create_AddCard(_dafny.Seq.UnicodeFromString(col), _dafny.Seq.UnicodeFromString(title)),
  MoveCard: (id, toCol, pos) => KanbanDomain.Action.create_MoveCard(new BigNumber(id), _dafny.Seq.UnicodeFromString(toCol), new BigNumber(pos)),

  // Model accessors
  GetCols: (m) => seqToArray(m.dtor_cols).map(x => dafnyStringToJs(x)),
  GetLanes: (m, key) => {
    const dafnyKey = _dafny.Seq.UnicodeFromString(key);
    if (m.dtor_lanes.contains(dafnyKey)) {
      const val = m.dtor_lanes.get(dafnyKey);
      return seqToArray(val).map(x => toNumber(x));
    }
    return null;
  },
  GetWip: (m, key) => {
    const dafnyKey = _dafny.Seq.UnicodeFromString(key);
    if (m.dtor_wip.contains(dafnyKey)) {
      const val = m.dtor_wip.get(dafnyKey);
      return toNumber(val);
    }
    return null;
  },
  GetCards: (m, key) => {
    const dafnyKey = new BigNumber(key);
    if (m.dtor_cards.contains(dafnyKey)) {
      const val = m.dtor_cards.get(dafnyKey);
      return cardToJson(val);
    }
    return null;
  },
  GetNextId: (m) => toNumber(m.dtor_nextId),

  // AppCore functions
  Init: () => KanbanAppCore.__default.Init(),
  Dispatch: (h, a) => KanbanAppCore.__default.Dispatch(h, a),
  Undo: (h) => KanbanAppCore.__default.Undo(h),
  Redo: (h) => KanbanAppCore.__default.Redo(h),
  Present: (h) => KanbanAppCore.__default.Present(h),
  CanUndo: (h) => KanbanAppCore.__default.CanUndo(h),
  CanRedo: (h) => KanbanAppCore.__default.CanRedo(h),
  GetLane: (m, col) => seqToArray(KanbanAppCore.__default.GetLane(m, _dafny.Seq.UnicodeFromString(col))).map(x => toNumber(x)),
  GetCardTitle: (m, id) => dafnyStringToJs(KanbanAppCore.__default.GetCardTitle(m, new BigNumber(id))),

  // Conversion functions
  cardToJson: cardToJson,
  cardFromJson: cardFromJson,
  modelToJson: modelToJson,
  modelFromJson: modelFromJson,
  actionToJson: actionToJson,
  actionFromJson: actionFromJson,
  historyToJson: historyToJson,
  historyFromJson: historyFromJson,
};

// Export internals for custom extensions
App._internal = { _dafny, KanbanDomain, KanbanKernel, KanbanAppCore };

export default App;
