// Generated by dafny2js
// Do not edit manually - regenerate from Dafny sources

import BigNumber from 'bignumber.js';

// Configure BigNumber as Dafny expects
BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });

// Import the generated code as raw text
import dafnyCode from './CanonReplay.cjs?raw';

// Set up the environment and evaluate the Dafny code
const require = (mod) => {
  if (mod === 'bignumber.js') return BigNumber;
  throw new Error(`Unknown module: ${mod}`);
};

// Create a function that evaluates the code with proper scope
const initDafny = new Function('require', `
  ${dafnyCode}
  return { _dafny, CanonDomain, Canon, CanonKernel, AppCore };
`);

const { _dafny, CanonDomain, Canon, CanonKernel, AppCore } = initDafny(require);


// ============================================================================
// Helpers
// ============================================================================

// Convert Dafny seq to JS array
const seqToArray = (seq) => {
  const arr = [];
  for (let i = 0; i < seq.length; i++) {
    arr.push(seq[i]);
  }
  return arr;
};

// Convert BigNumber to JS number
const toNumber = (bn) => {
  if (bn && typeof bn.toNumber === 'function') {
    return bn.toNumber();
  }
  return bn;
};

// Convert Dafny string to JS string
const dafnyStringToJs = (seq) => {
  if (typeof seq === 'string') return seq;
  if (seq.toVerbatimString) return seq.toVerbatimString(false);
  return Array.from(seq).join('');
};

// ============================================================================
// Datatype Conversions
// ============================================================================

const actionFromJson = (json) => {
  switch (json.type) {
    case 'AddNode': {
      return CanonDomain.Action.create_AddNode(
        _dafny.Seq.UnicodeFromString(json.id),
        new BigNumber(json.x),
        new BigNumber(json.y)
      );
    }
    case 'AddAlign': {
      return CanonDomain.Action.create_AddAlign(
        _dafny.Seq.of(...(json.sel || []).map(x => _dafny.Seq.UnicodeFromString(x)))
      );
    }
    case 'AddEvenSpace': {
      return CanonDomain.Action.create_AddEvenSpace(
        _dafny.Seq.of(...(json.sel || []).map(x => _dafny.Seq.UnicodeFromString(x)))
      );
    }
    case 'AddEdge': {
      return CanonDomain.Action.create_AddEdge(
        _dafny.Seq.UnicodeFromString(json.from),
        _dafny.Seq.UnicodeFromString(json.to)
      );
    }
    case 'DeleteConstraint': {
      return CanonDomain.Action.create_DeleteConstraint(
        new BigNumber(json.cid)
      );
    }
    case 'DeleteEdge': {
      return CanonDomain.Action.create_DeleteEdge(
        _dafny.Seq.UnicodeFromString(json.from),
        _dafny.Seq.UnicodeFromString(json.to)
      );
    }
    case 'RemoveNode': {
      return CanonDomain.Action.create_RemoveNode(
        _dafny.Seq.UnicodeFromString(json.nodeId)
      );
    }
    case 'MoveNode': {
      return CanonDomain.Action.create_MoveNode(
        _dafny.Seq.UnicodeFromString(json.id),
        new BigNumber(json.newX),
        new BigNumber(json.newY)
      );
    }
    default:
      throw new Error(`Unknown Action type: ${json.type}`);
  }
};

const actionToJson = (value) => {
  if (value.is_AddNode) {
    return {
      type: 'AddNode',
      id: dafnyStringToJs(value.dtor_id),
      x: toNumber(value.dtor_x),
      y: toNumber(value.dtor_y)
    };
  } else if (value.is_AddAlign) {
    return {
      type: 'AddAlign',
      sel: seqToArray(value.dtor_sel).map(x => dafnyStringToJs(x))
    };
  } else if (value.is_AddEvenSpace) {
    return {
      type: 'AddEvenSpace',
      sel: seqToArray(value.dtor_sel).map(x => dafnyStringToJs(x))
    };
  } else if (value.is_AddEdge) {
    return {
      type: 'AddEdge',
      from: dafnyStringToJs(value.dtor_from),
      to: dafnyStringToJs(value.dtor_to)
    };
  } else if (value.is_DeleteConstraint) {
    return {
      type: 'DeleteConstraint',
      cid: toNumber(value.dtor_cid)
    };
  } else if (value.is_DeleteEdge) {
    return {
      type: 'DeleteEdge',
      from: dafnyStringToJs(value.dtor_from),
      to: dafnyStringToJs(value.dtor_to)
    };
  } else if (value.is_RemoveNode) {
    return {
      type: 'RemoveNode',
      nodeId: dafnyStringToJs(value.dtor_nodeId)
    };
  } else if (value.is_MoveNode) {
    return {
      type: 'MoveNode',
      id: dafnyStringToJs(value.dtor_id),
      newX: toNumber(value.dtor_newX),
      newY: toNumber(value.dtor_newY)
    };
  }
  return { type: 'Unknown' };
};

const nodeFromJson = (json) => {
  return Canon.Node.create_Node(
    _dafny.Seq.UnicodeFromString(json.id),
    new BigNumber(json.x),
    new BigNumber(json.y)
  );
};

const nodeToJson = (value) => {
  return {
    id: dafnyStringToJs(value.dtor_id),
    x: toNumber(value.dtor_x),
    y: toNumber(value.dtor_y)
  };
};

const axisFromJson = (json) => {
  switch (json) {
    case 'X':
      return Canon.Axis.create_X();
    case 'Y':
      return Canon.Axis.create_Y();
    default:
      throw new Error(`Unknown Axis: ${json}`);
  }
};

const axisToJson = (value) => {
  if (value.is_X) {
    return 'X';
  } else if (value.is_Y) {
    return 'Y';
  }
  return 'Unknown';
};

const constraintFromJson = (json) => {
  switch (json.type) {
    case 'Align': {
      return Canon.Constraint.create_Align(
        new BigNumber(json.cid),
        _dafny.Seq.of(...(json.targets || []).map(x => _dafny.Seq.UnicodeFromString(x))),
        axisFromJson(json.axis)
      );
    }
    case 'EvenSpace': {
      return Canon.Constraint.create_EvenSpace(
        new BigNumber(json.cid),
        _dafny.Seq.of(...(json.targets || []).map(x => _dafny.Seq.UnicodeFromString(x))),
        axisFromJson(json.axis)
      );
    }
    default:
      throw new Error(`Unknown Constraint type: ${json.type}`);
  }
};

const constraintToJson = (value) => {
  if (value.is_Align) {
    return {
      type: 'Align',
      cid: toNumber(value.dtor_cid),
      targets: seqToArray(value.dtor_targets).map(x => dafnyStringToJs(x)),
      axis: axisToJson(value.dtor_axis)
    };
  } else if (value.is_EvenSpace) {
    return {
      type: 'EvenSpace',
      cid: toNumber(value.dtor_cid),
      targets: seqToArray(value.dtor_targets).map(x => dafnyStringToJs(x)),
      axis: axisToJson(value.dtor_axis)
    };
  }
  return { type: 'Unknown' };
};

const edgeFromJson = (json) => {
  return Canon.Edge.create_Edge(
    _dafny.Seq.UnicodeFromString(json.from),
    _dafny.Seq.UnicodeFromString(json.to)
  );
};

const edgeToJson = (value) => {
  return {
    from: dafnyStringToJs(value.dtor_from),
    to: dafnyStringToJs(value.dtor_to)
  };
};

const modelFromJson = (json) => {
  let __nodes = _dafny.Map.Empty;
  for (const [k, v] of Object.entries(json.nodes || {})) {
    const key = _dafny.Seq.UnicodeFromString(k);
    const val = nodeFromJson(v);
    __nodes = __nodes.update(key, val);
  }
  return Canon.Model.create_Model(
    __nodes,
    _dafny.Seq.of(...(json.edges || []).map(x => edgeFromJson(x))),
    _dafny.Seq.of(...(json.constraints || []).map(x => constraintFromJson(x))),
    new BigNumber(json.nextCid)
  );
};

const modelToJson = (value) => {
  const __nodesJson = {};
  if (value.dtor_nodes && value.dtor_nodes.Keys) {
    for (const k of value.dtor_nodes.Keys.Elements) {
      const v = value.dtor_nodes.get(k);
      __nodesJson[dafnyStringToJs(k)] = nodeToJson(v);
    }
  }
  return {
    nodes: __nodesJson,
    edges: seqToArray(value.dtor_edges).map(x => edgeToJson(x)),
    constraints: seqToArray(value.dtor_constraints).map(x => constraintToJson(x)),
    nextCid: toNumber(value.dtor_nextCid)
  };
};

const historyFromJson = (json) => {
  return CanonKernel.History.create_History(
    _dafny.Seq.of(...(json.past || []).map(x => modelFromJson(x))),
    modelFromJson(json.present),
    _dafny.Seq.of(...(json.future || []).map(x => modelFromJson(x)))
  );
};

const historyToJson = (value) => {
  return {
    past: seqToArray(value.dtor_past).map(x => modelToJson(x)),
    present: modelToJson(value.dtor_present),
    future: seqToArray(value.dtor_future).map(x => modelToJson(x))
  };
};

// ============================================================================
// API Wrapper
// ============================================================================

const App = {
  // Action constructors
  AddNode: (id, x, y) => CanonDomain.Action.create_AddNode(_dafny.Seq.UnicodeFromString(id), new BigNumber(x), new BigNumber(y)),
  AddAlign: (sel) => CanonDomain.Action.create_AddAlign(_dafny.Seq.of(...(sel || []).map(x => _dafny.Seq.UnicodeFromString(x)))),
  AddEvenSpace: (sel) => CanonDomain.Action.create_AddEvenSpace(_dafny.Seq.of(...(sel || []).map(x => _dafny.Seq.UnicodeFromString(x)))),
  AddEdge: (from, to) => CanonDomain.Action.create_AddEdge(_dafny.Seq.UnicodeFromString(from), _dafny.Seq.UnicodeFromString(to)),
  DeleteConstraint: (cid) => CanonDomain.Action.create_DeleteConstraint(new BigNumber(cid)),
  DeleteEdge: (from, to) => CanonDomain.Action.create_DeleteEdge(_dafny.Seq.UnicodeFromString(from), _dafny.Seq.UnicodeFromString(to)),
  RemoveNode: (nodeId) => CanonDomain.Action.create_RemoveNode(_dafny.Seq.UnicodeFromString(nodeId)),
  MoveNode: (id, newX, newY) => CanonDomain.Action.create_MoveNode(_dafny.Seq.UnicodeFromString(id), new BigNumber(newX), new BigNumber(newY)),

  // AppCore functions
  Init: () => AppCore.__default.Init(),
  Dispatch: (h, a) => AppCore.__default.Dispatch(h, a),
  Undo: (h) => AppCore.__default.Undo(h),
  Redo: (h) => AppCore.__default.Redo(h),
  CanonHistory: (h) => AppCore.__default.CanonHistory(h),
  Present: (h) => AppCore.__default.Present(h),
  CanUndo: (h) => AppCore.__default.CanUndo(h),
  CanRedo: (h) => AppCore.__default.CanRedo(h),
  Nodes: (h) => AppCore.__default.Nodes(h),
  Edges: (h) => seqToArray(AppCore.__default.Edges(h)).map(x => edgeToJson(x)),
  Constraints: (h) => seqToArray(AppCore.__default.Constraints(h)).map(x => constraintToJson(x)),

  // Conversion functions
  actionToJson: actionToJson,
  actionFromJson: actionFromJson,
  nodeToJson: nodeToJson,
  nodeFromJson: nodeFromJson,
  axisToJson: axisToJson,
  axisFromJson: axisFromJson,
  constraintToJson: constraintToJson,
  constraintFromJson: constraintFromJson,
  edgeToJson: edgeToJson,
  edgeFromJson: edgeFromJson,
  modelToJson: modelToJson,
  modelFromJson: modelFromJson,
  historyToJson: historyToJson,
  historyFromJson: historyFromJson,
};

// Export internals for custom extensions
App._internal = { _dafny, CanonDomain, Canon, CanonKernel, AppCore };

export default App;
